language: c++
sudo: required
dist: trusty
install:
- sudo apt-get update
- sudo apt-get install automake
- sudo apt-get install autoconf
- sudo apt-get install libtool
- sudo apt-get install bison
- sudo apt-get install flex
- sudo apt-get install xutils-dev
- sudo apt-get install libpciaccess-dev
- sudo apt-get install libomxil-bellagio-dev
- sudo apt-get install llvm
- sudo apt-get install python-pip
- sudo apt-get install python3-mako
- sudo apt-get install python-mako
- ls /usr/lib/python2.7/dist-packages/mako
- sudo apt-get install tree
script:
- export HWC_BUILD_DIR=$TRAVIS_BUILD_DIR/../
- export WLD=$TRAVIS_BUILD_DIR/../hwc-install
- export LD_LIBRARY_PATH=$WLD/lib
- export PKG_CONFIG_PATH=$WLD/lib/pkgconfig/:$WLD/share/pkgconfig
- export PATH=$WLD/bin:$PATH
- export ACLOCAL_PATH=$WLD/share/aclocal
- export ACLOCAL="aclocal -I $ACLOCAL_PATH"
- mkdir -p $HWC_BUILD_DIR
- mkdir -p $WLD/share/aclocal
- export DRV_I915=1
- git clone https://github.com/android-ia/device-androidia-kernel.git $HWC_BUILD_DIR/linux
- git clone https://github.com/android-ia/external-libdrm.git $HWC_BUILD_DIR/libdrm
- git clone https://github.com/android-ia/external-mesa.git $HWC_BUILD_DIR/mesa
- git clone https://github.com/01org/minigbm.git $HWC_BUILD_DIR/minigbm
- git clone https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers.git $HWC_BUILD_DIR/vulkan
- cp travisci/resources/linux.cfg $HWC_BUILD_DIR/linux/.config
- pushd $HWC_BUILD_DIR/linux/
- no "" | make oldconfig
- make -j5
- make headers_install INSTALL_HDR_PATH=$WLD
- popd
- pushd $HWC_BUILD_DIR/libdrm
- ./autogen.sh --disable-radeon --disable-nouveau --enable-udev -enable-libkms --prefix=$WLD
- make -j5 && make install
- popd
- pushd $HWC_BUILD_DIR/mesa
- ./autogen.sh --prefix=$WLD --enable-gles2 --disable-gallium-egl --with-egl-platforms=surfaceless --disable-dri3 --enable-shared-glapi --enable-texture-float --with-driver=dri --disable-glu --disable-glut --without-demos --disable-option-checking --disable-glx --enable-glx-tls --disable-nouveau --disable-gbm --with-dri-drivers=i965 --with-gallium-drivers=
- make -j4 && make install
- popd
- pushd $HWC_BUILD_DIR/minigbm
- make CFLAGS=-DDRV_I915=1
- make install DESTDIR=$WLD LIBDIR=lib/
- popd
- ./autogen.sh --prefix=$WLD
- make -j8
- tree $WLD
branches:
  only:
  - travisci
