language: c++
sudo: required
install:
- sudo apt-get install autoconf
- sudo apt-get install libtool
- sudo apt-get install bison
- sudo apt-get install flex
- sudo apt-get install python-mako
- sudo apt-get install libpciaccess-dev
- sudo apt-get install libomxil-bellagio-dev
- sudo apt-get install llvm
branches:
  only:
  - travisci
